// <auto-generated />
namespace Zero_Hunger_Mid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editannote2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editannote2));
        
        string IMigrationMetadata.Id
        {
            get { return "202303241903122_editannote2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
